### PR TITLE
New Feature Popup

### PR DESCRIPTION
**Pull request by miguelesco**
## What's new

- Add Script.js that import all the .js files use in the project.
- Add js functions to display all the cards dynamically.
- Click on the project Button you can see all the details of the project in the popup.
- Popup Responsive.

### CODE REVIEW

**Review by vichuge — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

mario_ladders

## Good points 👍 
You used proper GitHub Flow ✔️
Your linter checks are all passing ✔️

## Aspects to improve ♻️

- [x] It looks like you have a bug with the images, I kindly invite you to fix it.
image

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, consider:
- [OPTIONAL] For the next project, I invite you to add better commit messages following the [good principles](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by miguelesco** [comment]
the images are working well on my side, I test in 3 different browsers and 2 laptops. Please try to open the index.html with a live server I recommend "Live Server extension" by Ritwick Dey for VScode, because I'm using javascript with modules and if you open the project without any type of server you will get cors errors for the modules.

image


image

**Comment by vichuge** [comment]
> the images are working well on my side, I test in 3 different browsers and 2 laptops. Please try to open the index.html with a live server I recommend "Live Server extension" by Ritwick Dey for VScode, because I'm using javascript with modules and if you open the project without any type of server you will get cors errors for the modules.
> 
> image
> 
> image

An easier way to avoid this problem is using Github pages and refreshing it when you make changes, next time, I invite you to use the GitHub pages 😄

**Review by vichuge — APPROVED** [review]
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

InbornCandidHornet-size_restricted

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
